services:

  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: minervamoney
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres-data: